<?php

// Robo47_Auth
define('TESTS_ROBO47_AUTH', true);
define('TESTS_ROBO47_AUTH_ADAPTER_ARRAY', true);

// Robo47_Application
define('TESTS_ROBO47_APPLICATION', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_AUTOLOADER', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_AUTOLOADERMULTI', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_CACHE', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_CACHEMULTI', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_CONFIG', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_OBJECT', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_OBJECTMULTI', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_LOG', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_ERRORHANDLER', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_HTMLPURIFIER', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_PLUGIN_ERRORHANDLER', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_SERVICE_AKISMET', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_SERVICE_GRAVATAR', true);
define('TESTS_ROBO47_APPLICATION_RESOURCE_SERVICE_BITLY', true);

// Robo47_Cache
define('TESTS_ROBO47_CACHE', true);
define('TESTS_ROBO47_CACHE_BACKEND_ARRAY', true);
define('TESTS_ROBO47_CACHE_DOCTRINEADAPTER', true);

// Robo47_Curl
define('TESTS_ROBO47_CURL', true);
define('TESTS_ROBO47_CURL_MULTI', true);

// Robo47_Controller
define('TESTS_ROBO47_CONTROLLER', true);
define('TESTS_ROBO47_CONTROLLER_ACTION_HELPER_URL', true);
define('TESTS_ROBO47_CONTROLLER_PLUGIN_TITLE', true);
define('TESTS_ROBO47_CONTROLLER_PLUGIN_TIDY', true);

// Robo47_Convert
define('TESTS_ROBO47_CONVERT', true);

// Robo47_Core
define('TESTS_ROBO47_CORE', true);

// Robo47_ErrorHandler
define('TESTS_ROBO47_ERRORHANDLER', true);

// Robo47_Exception
define('TESTS_ROBO47_EXCEPTION', true);

// Robo47_ErrorException
define('TESTS_ROBO47_ERROREXCEPTION', true);

// Robo47_Exiftool
define('TESTS_ROBO47_EXIFTOOL', true);
define('TESTS_CONFIG_ROBO47_EXIFTOOL_EXIFTOOLPATH', '/usr/bin/exiftool');

// Robo47_Form
define('TESTS_ROBO47_FORM', true);
define('TESTS_ROBO47_FORM_DECORATOR_INFO', true);
define('TESTS_ROBO47_FORM_ELEMENT_CKEDITOR', true);

// Robo47_Filter
define('TESTS_ROBO47_FILTER', true);
define('TESTS_ROBO47_FILTER_HTMLPURIFIER', true);
define('TESTS_ROBO47_FILTER_SANITIZEURL', true);
define('TESTS_ROBO47_FILTER_URLSCHEME', true);
define('TESTS_ROBO47_FILTER_TIDY', true);

// Robo47_Loader
define('TESTS_ROBO47_LOADER', true);
define('TESTS_ROBO47_LOADER_AUTOLOADER_EZC', true);
define('TESTS_ROBO47_LOADER_AUTOLOADER_HTMLPURIFIER', true);

// Robo47_Log
define('TESTS_ROBO47_LOG', true);
define('TESTS_ROBO47_LOG_WRITER_ABSTRACT', true);
define('TESTS_ROBO47_LOG_WRITER_MOCK', true);
define('TESTS_ROBO47_LOG_WRITER_DOCTRINETABLE', true);
define('TESTS_ROBO47_LOG_FILTER_MOCK', true);
define('TESTS_ROBO47_LOG_FILTER_CATEGORY', true);
define('TESTS_ROBO47_LOG_FILTER_VALIDATEPROXY', true);

// Robo47_Mail
define('TESTS_ROBO47_MAIL', true);
define('TESTS_ROBO47_MAIL_TRANSPORT_MOCKSIMPLE', true);
define('TESTS_ROBO47_MAIL_TRANSPORT_LOG', true);
define('TESTS_ROBO47_MAIL_TRANSPORT_LOG_FORMATTER_SERIALIZE', true);
define('TESTS_ROBO47_MAIL_TRANSPORT_LOG_FORMATTER_SIMPLE', true);
define('TESTS_ROBO47_MAIL_TRANSPORT_MULTI', true);

// Robo47_Mock
define('TESTS_ROBO47_MOCK', true);

// Robo47_Paginator
define('TESTS_ROBO47_PAGINATOR', true);
define('TESTS_ROBO47_PAGINATOR_ADAPTER_DOCTRINEQUERY', true);
define('TESTS_ROBO47_PAGINATOR_ADAPTER_DOCTRINETABLE', true);

// Robo47_Service
define('TESTS_ROBO47_SERVICE', true);
define('TESTS_ROBO47_SERVICE_BITLY', true);
define('TESTS_ROBO47_SERVICE_GRAVATAR', true);

// Robo47_Validate
define('TESTS_ROBO47_VALIDATE', true);
define('TESTS_ROBO47_VALIDATE_URI', true);
define('TESTS_ROBO47_VALIDATE_STRINGCONTAINS', true);
define('TESTS_ROBO47_VALIDATE_STRINGNOTCONTAINS', true);
define('TESTS_ROBO47_VALIDATE_MAXLINELENGTH', true);
define('TESTS_ROBO47_VALIDATE_MOCK', true);
define('TESTS_ROBO47_VALIDATE_DOCTRINE_ABSTRACT', true);
define('TESTS_ROBO47_VALIDATE_DOCTRINE_RECORDEXISTS', true);
define('TESTS_ROBO47_VALIDATE_DOCTRINE_NORECORDEXISTS', true);

// Robo47_View
define('TESTS_ROBO47_VIEW', true);
define('TESTS_ROBO47_VIEW_HELPER_ANCHOR', true);
define('TESTS_ROBO47_VIEW_HELPER_CDN', true);
define('TESTS_ROBO47_VIEW_HELPER_GLOBALS', true);
define('TESTS_ROBO47_VIEW_HELPER_CKEDITOR', true);
define('TESTS_ROBO47_VIEW_HELPER_URL', true);
define('TESTS_ROBO47_VIEW_HELPER_GRAVATAR', true);